# Copyright (C) 2024 psionicprjkt

name: ci-macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Set up SSH
        uses: fastai/workflows/ssh@master
        with:
          ssh_key: ${{ secrets.SSH_KEY }}
          key_file: id_ecdsa

      - name: Setup Debug Session
        uses: mxschmitt/action-tmate@master
